<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_search_menuQuickSearchmenuQuickSearch</name>
   <tag></tag>
   <elementGuidId>beea8d95-1601-40b6-aec5-abea2f450dbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menuQuickSearch_menuQuickSearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='menuQuickSearch_menuQuickSearch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d29133b8-3828-43f4-89cf-3d00e5382041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>4af87feb-1c8e-4be8-8654-7a890a6cfc8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b0edb6cb-1764-49aa-a438-1ffb8c3f1f8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>menuQuickSearch[menuQuickSearch]</value>
      <webElementGuid>1d39d210-a5c2-484f-8a98-de667d0c3110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menuQuickSearch_menuQuickSearch</value>
      <webElementGuid>abc8b2d9-dfa2-4b4c-83fd-6559b91c1151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>menuQuickSearchResultList</value>
      <webElementGuid>af82fd02-8e76-4777-8c0b-84480727a79b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>both</value>
      <webElementGuid>5e7a9139-c14a-40bd-b580-4f87fbd59758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menuQuickSearch_menuQuickSearch&quot;)</value>
      <webElementGuid>fa34d575-26a5-42f6-9be6-60a6eead36ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='menuQuickSearch_menuQuickSearch']</value>
      <webElementGuid>01871bc0-e876-447e-9f6f-241e97c919d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='left-menu']/div[3]/div[2]/input</value>
      <webElementGuid>0fc77ed3-d938-4111-b475-29f82f34586f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8c1a6aea-2f92-4daf-9f2d-4c8a0212e158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Search' and @type = 'text' and @name = 'menuQuickSearch[menuQuickSearch]' and @id = 'menuQuickSearch_menuQuickSearch']</value>
      <webElementGuid>72cb95d0-78a2-498b-8ec4-30271ef107a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
