<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_EducationEmployee Management  Qualifications</name>
   <tag></tag>
   <elementGuidId>47739a01-02c7-452a-b0ef-159d4d65ca8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#autoComplete_result_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='autoComplete_result_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Education Employee Management > Qualifications&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>7a49828a-8ee4-495b-b8e9-72f53da0b987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>autoComplete_result_0</value>
      <webElementGuid>8a2d26b1-b3ec-4727-ae51-7f8f87da0f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>9ecb2c07-c983-4432-aa32-4e6b52649e02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menuSearchResultItem</value>
      <webElementGuid>9d645698-df8f-48b3-91ee-a5352cbb5c7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EducationEmployee Management > Qualifications</value>
      <webElementGuid>47f650b1-8a2b-4553-bec4-34c91754b959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;autoComplete_result_0&quot;)</value>
      <webElementGuid>75cb9864-a3bd-40be-9b5c-fe3baa046104</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='autoComplete_result_0']</value>
      <webElementGuid>463869dd-fa09-4e96-b846-658075d8eba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='menuQuickSearchResultList']/li</value>
      <webElementGuid>d2fbcbb6-b032-4a4f-8470-f86676c6f09b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='search'])[1]/following::li[1]</value>
      <webElementGuid>6ef97e2f-4880-469e-b970-aee90c8c2d99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regional HR Manager'])[1]/following::li[1]</value>
      <webElementGuid>ffac3718-37ef-45dd-b245-11405c5fc499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>a592d438-e111-4229-9c3d-ac172760ffde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'autoComplete_result_0' and (text() = 'EducationEmployee Management > Qualifications' or . = 'EducationEmployee Management > Qualifications')]</value>
      <webElementGuid>24122ac8-cf04-45d4-ad9d-3f246fb51655</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
