<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_more_horizSelect AllJob Category   arro_cc7f56</name>
   <tag></tag>
   <elementGuidId>b808a5c8-afb5-4048-9ea1-096e8c16e90f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jobcategoryDiv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='jobcategoryDiv']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#jobcategoryDiv</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>be1d0853-bb56-44ee-b996-baee4431e132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jobcategoryDiv</value>
      <webElementGuid>b92d8b36-4e23-4c1c-984b-3c5849dc6ac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>more_horizSelect AllJob Category   arrow_upward hghohrm_edit  Craft Workersohrm_edit  dadsaohrm_edit  fsohrm_edit  JC0ohrm_edit  JC1ohrm_edit  JC2ohrm_edit  JC3ohrm_edit  Laborers and Helpersohrm_edit  NJCohrm_edit  Office and Clerical Workersohrm_edit  Officials and Managersohrm_edit  Operativesohrm_edit  Professionalsohrm_edit  Sales Workersohrm_edit  Service Workersohrm_edit  Software Enggohrm_edit  Software Engineerohrm_edit  Techniciansohrm_edit Rows per page▼1020501001020501001 - 19 of 19add</value>
      <webElementGuid>31cf4da3-e6e0-44a5-b941-46858852cfbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jobcategoryDiv&quot;)</value>
      <webElementGuid>b47064f0-c693-4e0b-87d1-62c9bfa2aeb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='jobcategoryDiv']</value>
      <webElementGuid>eb0b1782-8c53-4f0b-a037-893362dc7511</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mount-vue-app']/ui-view/div/div</value>
      <webElementGuid>da010ea3-a13c-4e56-ab96-0e9c2ceeacc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Timesheet'])[2]/following::div[7]</value>
      <webElementGuid>ecdae8d0-a942-4e8c-870f-758f41471e2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit Request'])[2]/following::div[10]</value>
      <webElementGuid>b15c664b-6775-4ba3-a949-e17553f4ff08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ui-view/div/div</value>
      <webElementGuid>a5b5836d-9cc1-4a89-8714-a55eaa40c4d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'jobcategoryDiv' and (text() = 'more_horizSelect AllJob Category   arrow_upward hghohrm_edit  Craft Workersohrm_edit  dadsaohrm_edit  fsohrm_edit  JC0ohrm_edit  JC1ohrm_edit  JC2ohrm_edit  JC3ohrm_edit  Laborers and Helpersohrm_edit  NJCohrm_edit  Office and Clerical Workersohrm_edit  Officials and Managersohrm_edit  Operativesohrm_edit  Professionalsohrm_edit  Sales Workersohrm_edit  Service Workersohrm_edit  Software Enggohrm_edit  Software Engineerohrm_edit  Techniciansohrm_edit Rows per page▼1020501001020501001 - 19 of 19add' or . = 'more_horizSelect AllJob Category   arrow_upward hghohrm_edit  Craft Workersohrm_edit  dadsaohrm_edit  fsohrm_edit  JC0ohrm_edit  JC1ohrm_edit  JC2ohrm_edit  JC3ohrm_edit  Laborers and Helpersohrm_edit  NJCohrm_edit  Office and Clerical Workersohrm_edit  Officials and Managersohrm_edit  Operativesohrm_edit  Professionalsohrm_edit  Sales Workersohrm_edit  Service Workersohrm_edit  Software Enggohrm_edit  Software Engineerohrm_edit  Techniciansohrm_edit Rows per page▼1020501001020501001 - 19 of 19add')]</value>
      <webElementGuid>473f78ef-ae7c-4f96-a7e1-bbbc44919e8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
