<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_more_horizSelect AllJob Category   arro_e3b70d</name>
   <tag></tag>
   <elementGuidId>a80b2798-1814-4582-bad9-ca610e30181a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.pim-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mount-vue-app']/ui-view/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#mount-vue-app div >> internal:has-text=&quot;more_horizSelect AllJob Category arrow_upward fsohrm_edit Craft Workersohrm_edit&quot;i >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d43c9be5-0949-4ca5-8ac8-9bfabc7a0a1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pim-container</value>
      <webElementGuid>ac8d799e-54a8-4785-96b7-2800a8fc9453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>more_horizSelect AllJob Category   arrow_upward fsohrm_edit  Craft Workersohrm_edit  Laborers and Helpersohrm_edit  NJCohrm_edit  Office and Clerical Workersohrm_edit  Officials and Managersohrm_edit  Operativesohrm_edit  Professionalsohrm_edit  Sales Workersohrm_edit  Service Workersohrm_edit  Software Enggohrm_edit  Software Engineerohrm_edit  Techniciansohrm_edit Rows per page▼1020501001020501001 - 13 of 13add</value>
      <webElementGuid>fc10b8fa-7879-4a9c-99bb-db5083bb7115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mount-vue-app&quot;)/ui-view[1]/div[@class=&quot;pim-container&quot;]</value>
      <webElementGuid>c3d89bde-7c47-43ff-b1c9-0ad1c7c8567e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mount-vue-app']/ui-view/div</value>
      <webElementGuid>88ca74a7-6f8b-4bbd-adb5-8b73824d124e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Timesheet'])[2]/following::div[6]</value>
      <webElementGuid>e107867d-3bb2-4abb-9bc6-b0e8ef6e2eb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit Request'])[2]/following::div[9]</value>
      <webElementGuid>3c4a6450-9b7a-4bba-a17b-3fbdf10143bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ui-view/div</value>
      <webElementGuid>fe5f3bd9-21b2-45aa-a45e-54c38ebdaf76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'more_horizSelect AllJob Category   arrow_upward fsohrm_edit  Craft Workersohrm_edit  Laborers and Helpersohrm_edit  NJCohrm_edit  Office and Clerical Workersohrm_edit  Officials and Managersohrm_edit  Operativesohrm_edit  Professionalsohrm_edit  Sales Workersohrm_edit  Service Workersohrm_edit  Software Enggohrm_edit  Software Engineerohrm_edit  Techniciansohrm_edit Rows per page▼1020501001020501001 - 13 of 13add' or . = 'more_horizSelect AllJob Category   arrow_upward fsohrm_edit  Craft Workersohrm_edit  Laborers and Helpersohrm_edit  NJCohrm_edit  Office and Clerical Workersohrm_edit  Officials and Managersohrm_edit  Operativesohrm_edit  Professionalsohrm_edit  Sales Workersohrm_edit  Service Workersohrm_edit  Software Enggohrm_edit  Software Engineerohrm_edit  Techniciansohrm_edit Rows per page▼1020501001020501001 - 13 of 13add')]</value>
      <webElementGuid>5c86e756-9fc5-4c55-a1aa-1d9bc1b6fc8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
