<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_hgh</name>
   <tag></tag>
   <elementGuidId>1cc95817-d017-4144-b587-7f3fb2d95e67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ng-include > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='jobcategoryDiv']/crud-panel/div/div/list/table/tbody/tr/td[2]/ng-include/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;hgh&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6a21afc0-6125-46c0-960c-efd7b3e48186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>hgh</value>
      <webElementGuid>7123236b-fa8e-45c2-89f0-3321157e10f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jobcategoryDiv&quot;)/crud-panel[1]/div[@class=&quot;form-div&quot;]/div[@class=&quot;list-container&quot;]/list[1]/table[@class=&quot;highlight bordered&quot;]/tbody[1]/tr[1]/td[2]/ng-include[1]/span[1]</value>
      <webElementGuid>2a5ae5d5-d175-467a-9aa4-09fa6883526b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jobcategoryDiv']/crud-panel/div/div/list/table/tbody/tr/td[2]/ng-include/span</value>
      <webElementGuid>b55b65da-312a-4a18-b167-6311b4b2fbdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='arrow_upward'])[1]/following::span[1]</value>
      <webElementGuid>ae2e731a-6df0-4e3e-b1ab-76b10f731055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ohrm_edit'])[1]/preceding::span[1]</value>
      <webElementGuid>d5b60545-fb3f-4c90-ba46-2bc55ba5fcf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Craft Workers'])[1]/preceding::span[1]</value>
      <webElementGuid>656866a8-f249-4b5d-bdb3-8a53701f9de3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='hgh']/parent::*</value>
      <webElementGuid>942311bf-c792-4116-95f7-841e3889b5fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-include/span</value>
      <webElementGuid>ff26c34a-eb24-4014-9f2f-a120da7a956a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'hgh' or . = 'hgh')]</value>
      <webElementGuid>0037ea71-8baf-4441-9abb-007432840fa7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
