<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Manage Job Categories</name>
   <tag></tag>
   <elementGuidId>bd6b623f-4e09-437a-8e62-b68667e7fdbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.menu-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='autoComplete_result_0']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Manage Job Categories&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3b67f53f-2b04-49a1-8d1b-ca9399cad783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-title</value>
      <webElementGuid>25ce2600-c290-4a68-9357-3f2691d9562c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Manage Job Categories</value>
      <webElementGuid>90910836-9400-4e5b-a819-1f3e2aff6255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;autoComplete_result_0&quot;)/div[@class=&quot;menu-title&quot;]</value>
      <webElementGuid>166c213e-21ed-4b03-914b-ada09da9f1fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='autoComplete_result_0']/div</value>
      <webElementGuid>f817284c-7c26-4cfd-a3aa-f32d3cc94f88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='search'])[1]/following::div[2]</value>
      <webElementGuid>af13276c-7f07-4adc-9d05-f69416132646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regional HR Manager'])[1]/following::div[7]</value>
      <webElementGuid>67e6491d-6c36-4533-97b8-ec601b3ea338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HR Administration > Job'])[1]/preceding::div[1]</value>
      <webElementGuid>b8d6f551-41df-4038-993d-b7172d68b764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='People Management'])[1]/preceding::div[2]</value>
      <webElementGuid>61393b95-1873-4931-bb2f-99952dc7b8d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Manage Job Categories']/parent::*</value>
      <webElementGuid>7e106335-03af-4557-9790-9c2dc281e089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div</value>
      <webElementGuid>2be74e5b-4d8c-40b9-a72b-e7284d1740c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Manage Job Categories' or . = 'Manage Job Categories')]</value>
      <webElementGuid>70ba2017-315f-46cf-bafd-351d3e42bab5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
