<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Save</name>
   <tag></tag>
   <elementGuidId>b0a75f91-e6b5-4d9e-afab-936c0ad006f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal1']/form/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.modal-action.waves-effect.waves-green.btn.primary-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Save&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ac23a022-c776-46be-bf0d-1b76e158db31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ohrm-save-form</name>
      <type>Main</type>
      <value>modal.save(educationModalForm)</value>
      <webElementGuid>924fc849-82f6-42d7-937e-e0a1321d8fb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>form-name</name>
      <type>Main</type>
      <value>educationModalForm</value>
      <webElementGuid>dda4902c-093d-46b1-b931-4b22f044d63e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>close-modal-on-click</name>
      <type>Main</type>
      <value>educationModalForm</value>
      <webElementGuid>5e31361b-305d-4daf-ad91-c8417ceebb79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-action waves-effect waves-green btn primary-btn</value>
      <webElementGuid>08bfc889-5d4f-465a-8187-1bbbf038bbda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>2bcb5a42-784c-4f0f-ba27-3343254df484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal1&quot;)/form[@class=&quot;ng-valid ng-valid-duplication-education ng-valid-schema-form ng-dirty ng-valid-parse&quot;]/div[@class=&quot;modal-footer&quot;]/a[@class=&quot;modal-action waves-effect waves-green btn primary-btn&quot;]</value>
      <webElementGuid>f896f85f-639e-49a2-9c00-6d45ebd6608d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal1']/form/div[2]/a</value>
      <webElementGuid>c67fc58e-8aae-45ce-b30e-b6eef540afd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Save')]</value>
      <webElementGuid>150e24dd-393e-4365-96db-967b82774ce3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::a[1]</value>
      <webElementGuid>5da11566-e5d3-4192-aacd-1d6ab0097e95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/preceding::a[1]</value>
      <webElementGuid>156fa9f0-6181-4658-b0fa-4073bd0c4818</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>8df3aafe-4956-41dd-a768-a75873709d24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[81]</value>
      <webElementGuid>5d8c877e-aa7b-48dd-9066-b918e40169d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/a</value>
      <webElementGuid>5790b33e-780f-4457-afa9-ded868278cb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>f40d66b1-4946-46fc-b8e7-c0283860ab92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[79]</value>
      <webElementGuid>c67e75ef-6f35-44b9-a7e8-83527ef085ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
