<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Yes, Delete_materialize-lean-overlay-1</name>
   <tag></tag>
   <elementGuidId>c28cd4e0-96cf-43da-92d7-f753bc09ed4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='materialize-lean-overlay-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#materialize-lean-overlay-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#materialize-lean-overlay-1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>150b7ead-fb6b-4b82-ba6f-65acbea25665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lean-overlay velocity-animating</value>
      <webElementGuid>9ae7b3fd-a8e3-442d-906d-8bc120c1c32f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>materialize-lean-overlay-1</value>
      <webElementGuid>95a9589f-399e-43a0-aceb-43a9f0fe7288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;materialize-lean-overlay-1&quot;)</value>
      <webElementGuid>16cb9c14-f40a-4b44-a615-5527eded0a25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='materialize-lean-overlay-1']</value>
      <webElementGuid>9c078751-f3f2-40a7-aa8a-cb2351cb4686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[50]</value>
      <webElementGuid>d7cda78b-3b89-4299-82cd-b9c537dde7a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'materialize-lean-overlay-1']</value>
      <webElementGuid>be2130b2-74ff-4545-bb98-28190f623e6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
