<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_ohrm_edit</name>
   <tag></tag>
   <elementGuidId>59ea0f7b-77f7-4ee1-b822-c1d208e433df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='educationsDiv']/crud-panel/div/div/list/table/tbody/tr/td[3]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.edit_item.tooltipped > i.material-icons</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Bachelor’s or equivalent ohrm_edit&quot;i] >> i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>c14e67d1-0716-474f-875f-af1201064701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>TD.class=='edit_item'?true:false</value>
      <webElementGuid>8086b9bd-888d-470f-b782-04693107dd32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons</value>
      <webElementGuid>857b6edf-e349-4ccf-8adc-735e726e66d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ohrm_edit</value>
      <webElementGuid>18c6e8c2-bbb8-4068-bb55-1ba2f00c3f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;educationsDiv&quot;)/crud-panel[1]/div[@class=&quot;form-div&quot;]/div[@class=&quot;list-container&quot;]/list[1]/table[@class=&quot;highlight bordered&quot;]/tbody[1]/tr[1]/td[@class=&quot;edit_item tooltipped&quot;]/i[@class=&quot;material-icons&quot;]</value>
      <webElementGuid>4cb5f191-8e44-45b2-bd07-43159e3aefa3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='educationsDiv']/crud-panel/div/div/list/table/tbody/tr/td[3]/i</value>
      <webElementGuid>6bea942c-56ea-46fc-a9c9-66eabad39cff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bachelor’s or equivalent'])[1]/following::i[1]</value>
      <webElementGuid>9d0a4921-0aca-4114-9198-513d9bf5ba3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='arrow_upward'])[1]/following::i[1]</value>
      <webElementGuid>9da2b6ed-ce03-40bb-9005-2e54c3a24476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/preceding::i[1]</value>
      <webElementGuid>cd068825-6328-49bc-b27a-bc3c38cb532c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dad'])[1]/preceding::i[1]</value>
      <webElementGuid>58806a16-265c-485a-b395-6a39d4582e5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ohrm_edit']/parent::*</value>
      <webElementGuid>fafafbd2-49dd-41c8-937b-c53b902fd0d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/i</value>
      <webElementGuid>7c225e98-5921-4563-9445-191fa08038bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = 'ohrm_edit' or . = 'ohrm_edit')]</value>
      <webElementGuid>0205ca66-d9e8-4fc5-a8f3-4639920cde50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='educationsDiv']/crud-panel/div/div/list/table/tbody/tr[3]/td[3]/i</value>
      <webElementGuid>f54decc5-d4ab-4500-9616-cbf4dad39765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lower secondary education'])[1]/following::i[1]</value>
      <webElementGuid>bb8294d1-6b7b-4c5c-9012-dc41ca16e0d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ohrm_edit'])[2]/following::i[1]</value>
      <webElementGuid>8c424970-c2c9-489e-9af1-912372ed31ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Primary education'])[1]/preceding::i[1]</value>
      <webElementGuid>7684e708-34bb-4fd2-ae99-74457d748c65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/i</value>
      <webElementGuid>2bd4714e-5a35-46b1-8a42-0b9689844bb7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
