<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_search</name>
   <tag></tag>
   <elementGuidId>825cc856-ba73-4a40-8e48-9b2289765aad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='left-menu']/div[3]/div/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.icon-holder > i.material-icons</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;search&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>3cc40024-b4a1-4beb-808b-a0b458e73444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons</value>
      <webElementGuid>0fe7e417-d539-4137-abd0-9cf9c02db969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>a5421fd7-54b3-43ae-95c0-eced58a71d9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;left-menu&quot;)/div[@class=&quot;sidebar-search&quot;]/div[@class=&quot;icon-holder&quot;]/i[@class=&quot;material-icons&quot;]</value>
      <webElementGuid>e82e3be8-a9e8-4666-9100-f7c8d0d023d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='left-menu']/div[3]/div/i</value>
      <webElementGuid>917ffa56-5fa7-4854-a8d9-c331f73d0e39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regional HR Manager'])[1]/following::i[1]</value>
      <webElementGuid>4abd7a94-c0c0-446b-ab3f-b8f0939bf0a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aaron Hamilton'])[1]/following::i[1]</value>
      <webElementGuid>007ab4a0-0b0a-4db5-9e55-1aa0b9bd8ed7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Education'])[1]/preceding::i[1]</value>
      <webElementGuid>8f710bd8-67b2-4532-b3f6-9638b4258d46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employee Management > Qualifications'])[1]/preceding::i[1]</value>
      <webElementGuid>346a3e53-2181-4a1e-9cac-20c398bed71f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='search']/parent::*</value>
      <webElementGuid>5f3a7e26-2ceb-42ca-a7ee-f9d8507cd49a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/i</value>
      <webElementGuid>f540a0d9-63f5-4720-b6d3-eaf6f137e9e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = 'search' or . = 'search')]</value>
      <webElementGuid>a6ce4685-34fc-41d4-a44d-cf3b246a2474</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
