<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Login_icon hide-icon</name>
   <tag></tag>
   <elementGuidId>4650985d-e0d4-4dc8-80d8-2aca9ae116dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='frmLogin']/div[2]/div/img[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.icon.hide-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;Hide Password&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>63c060f2-fbb6-4ac3-b89e-450d651e4c08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon hide-icon</value>
      <webElementGuid>20f333f0-b98c-45ca-a3f5-bc7c3e67101f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Hide Password</value>
      <webElementGuid>ec5f161f-b335-440f-b369-cba01f16a141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/webres_65f025a10f6573.94024044/themes/default/images/login/oxd/visibility-off.svg</value>
      <webElementGuid>570464aa-c51e-43f3-82e0-db68d3f9cd86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmLogin&quot;)/div[@class=&quot;input-field&quot;]/div[@class=&quot;visibility-holder password-visible&quot;]/img[@class=&quot;icon hide-icon&quot;]</value>
      <webElementGuid>de85c5de-6639-41c7-ad08-472df1535a61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmLogin']/div[2]/div/img[2]</value>
      <webElementGuid>789c96a0-d822-4c36-8595-d792551002cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='Hide Password']</value>
      <webElementGuid>0da5311e-58b2-4a3b-89b4-d30da8e63cb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img[2]</value>
      <webElementGuid>f92b3510-e838-4e43-a7c3-47818089d4e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@title = 'Hide Password' and @src = '/webres_65f025a10f6573.94024044/themes/default/images/login/oxd/visibility-off.svg']</value>
      <webElementGuid>d010c3d6-5a81-4506-a6bd-cea935d80e0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
