<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Level of Education   arrow_upward</name>
   <tag></tag>
   <elementGuidId>264b0e2f-ce57-425c-a975-bfe8d680c5f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>th.row-name.sortable</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='educationsDiv']/crud-panel/div/div/list/table/thead/tr/th[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Level of Education arrow_upward&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>775001f0-dc00-4901-996a-7b6b98bea2b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-repeat</name>
      <type>Main</type>
      <value>listField in listData.listFields</value>
      <webElementGuid>5cd1f86a-efb8-4ff8-b355-006606f923a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-field</name>
      <type>Main</type>
      <value>level</value>
      <webElementGuid>bb0f8375-c1c5-4db0-a023-03c81efdf777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2c6ec261-9939-422a-82ca-da775e965c7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>list.fetchData(listField.name, listField.sortAction, listField.sortable, listData.pagination)</value>
      <webElementGuid>93b94ce3-a162-4b5f-92d8-ef2c4f0496d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row-name sortable</value>
      <webElementGuid>0ff26a11-95c1-4bfa-af49-87dbaeaa2133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{sortable: listField.sortable}</value>
      <webElementGuid>c30f4875-bd4a-4ba0-9157-75845e8a5445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>(listField.hideField==true?false:true) &amp;&amp; (listField.hideHeader==true?false:true)</value>
      <webElementGuid>63cb8e7a-5622-4c61-adb8-1041afb90573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Level of Education   arrow_upward</value>
      <webElementGuid>aa1ef9cd-e5e0-4c45-8085-0c852168863a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;educationsDiv&quot;)/crud-panel[1]/div[@class=&quot;form-div&quot;]/div[@class=&quot;list-container&quot;]/list[1]/table[@class=&quot;highlight bordered&quot;]/thead[1]/tr[1]/th[@class=&quot;row-name sortable&quot;]</value>
      <webElementGuid>7ed68948-1b31-42a9-9546-23ba29ce20a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='educationsDiv']/crud-panel/div/div/list/table/thead/tr/th[2]</value>
      <webElementGuid>44a258c3-85d2-4a6b-b317-64e481c6a1fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select All'])[1]/following::th[1]</value>
      <webElementGuid>1a234eeb-9348-4a0b-b14e-e88b0569536f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='more_horiz'])[1]/following::th[1]</value>
      <webElementGuid>546b5f80-a94f-4ee9-8f70-8fd50ea73f98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dad'])[1]/preceding::th[2]</value>
      <webElementGuid>5973d4ad-8281-49b6-a8e2-e98d7433587e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Level of Education']/parent::*</value>
      <webElementGuid>80c7201c-6549-438a-941c-0d1042799d83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[2]</value>
      <webElementGuid>05f1a7f9-0670-4121-8a8d-94112a77e2de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'Level of Education   arrow_upward' or . = 'Level of Education   arrow_upward')]</value>
      <webElementGuid>68d2343d-95c4-4d00-be2b-eb8373130583</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
