<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_ohrm_edit</name>
   <tag></tag>
   <elementGuidId>2b302d57-7965-4f28-9454-e602be898feb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='educationsDiv']/crud-panel/div/div/list/table/tbody/tr/td[3]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.edit_item.tooltipped > i.material-icons</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Bachelor’s or equivalent edit ohrm_edit&quot;i] >> i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>b1c3003e-21b6-4e50-814f-fb811e9878a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>TD.class=='edit_item'?true:false</value>
      <webElementGuid>b301a2f0-b949-4a2e-b4d8-be36e8a6a4c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons</value>
      <webElementGuid>14d21bf7-7f36-4440-afc5-b3bc56a8fba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ohrm_edit</value>
      <webElementGuid>6383db2a-a3d9-49ce-9ea4-b4238f193f68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;educationsDiv&quot;)/crud-panel[1]/div[@class=&quot;form-div&quot;]/div[@class=&quot;list-container&quot;]/list[1]/table[@class=&quot;highlight bordered&quot;]/tbody[1]/tr[1]/td[@class=&quot;edit_item tooltipped&quot;]/i[@class=&quot;material-icons&quot;]</value>
      <webElementGuid>f62e7362-3c51-494f-9a3e-7e4588a4cb53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='educationsDiv']/crud-panel/div/div/list/table/tbody/tr/td[3]/i</value>
      <webElementGuid>dc652192-60b7-4acf-b2ac-4ea95f045ae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bachelor’s or equivalent edit'])[1]/following::i[1]</value>
      <webElementGuid>c1acc70c-2152-4f3d-ad94-08d09243133a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='arrow_upward'])[1]/following::i[1]</value>
      <webElementGuid>e5a6a3ac-a139-45f2-a0b0-7fdf35c4b299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/preceding::i[1]</value>
      <webElementGuid>3f05f94e-cd44-474b-b6d2-e7c8ccaabef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dad'])[1]/preceding::i[1]</value>
      <webElementGuid>99925c3b-f0be-4417-a8fd-d50abdc7589c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ohrm_edit']/parent::*</value>
      <webElementGuid>ae0ce634-e08e-478d-bb8d-09e42d15fcd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/i</value>
      <webElementGuid>76dbd060-7904-4f23-aea6-2834bffdc115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = 'ohrm_edit' or . = 'ohrm_edit')]</value>
      <webElementGuid>7331d878-c0ec-4929-a4fb-9a79be716ff6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
