<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Cancel_materialize-lean-overlay-1</name>
   <tag></tag>
   <elementGuidId>7e675f39-0f08-45ff-ac6c-193e8ee05a3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#materialize-lean-overlay-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='materialize-lean-overlay-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#materialize-lean-overlay-1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1029e037-c0ea-41ed-bd8b-a26c235289a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lean-overlay</value>
      <webElementGuid>7f54c3f2-ce43-49bb-87b5-b77bfd70e14e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>materialize-lean-overlay-1</value>
      <webElementGuid>be0534d1-2a0f-4f75-b7ab-006d65687141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;materialize-lean-overlay-1&quot;)</value>
      <webElementGuid>79235716-a416-469e-ace6-9c04087e964d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='materialize-lean-overlay-1']</value>
      <webElementGuid>cf553ed5-8f47-47de-90ad-d47ec29d7329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[50]</value>
      <webElementGuid>0919235b-43f0-4c3f-ae8a-16aa21d647a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'materialize-lean-overlay-1']</value>
      <webElementGuid>fdf9bf37-ab47-4c3f-a114-c96f97679055</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
