<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Edit Education_name</name>
   <tag></tag>
   <elementGuidId>85bcc923-3557-46e9-922c-2edfc2a120be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Level of Education*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>301b25bb-84bb-441e-b553-3318acf8c0a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>790baf27-928a-4ca4-af31-c5cbf6900d5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sf-changed</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>8269e5d0-8ebd-40ec-9892-667e48420b8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a3d76764-b0d7-4ae9-9543-fccb8f1e74cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>form.readonly</value>
      <webElementGuid>d351d466-8b72-4e39-9006-17b7392278f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>schema-validate</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>d19f098f-120d-4dc7-bd4f-16551d6e699d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>model['name']</value>
      <webElementGuid>cdaa91e4-b145-489a-a63d-93498bf20d7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model-options</name>
      <type>Main</type>
      <value>form.ngModelOptions</value>
      <webElementGuid>4f0c2f14-b6a4-44f6-9322-fb3e29c7883d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ohrm-make-element-non-pristine</name>
      <type>Main</type>
      <value>form.removePristine</value>
      <webElementGuid>57693b4f-bf60-4002-9e3d-4ffd81504018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-autocomplete</name>
      <type>Main</type>
      <value>{{form.autocompleteOff}}</value>
      <webElementGuid>f71a8d71-af60-47da-a184-be2d49a71ead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-blur</name>
      <type>Main</type>
      <value>form.onBlur()</value>
      <webElementGuid>b65bd045-a8c3-43fd-a8d7-4c4c06b2a016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-not-empty ng-valid-duplication-education ng-valid-schema-form</value>
      <webElementGuid>7ed346bb-f69c-4145-9421-3b57f9fb4d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;name&quot;)</value>
      <webElementGuid>90894fab-3fe5-433c-81f9-4f4b4a8664cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='name']</value>
      <webElementGuid>d7f3d9d4-76c8-4be7-93e2-b7c27809aca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal1']/form/div/div/materializecss-decorator/div/sf-decorator/div/input</value>
      <webElementGuid>0a22e461-1ca7-4d65-a155-a7124bff7147</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//sf-decorator/div/input</value>
      <webElementGuid>f7df3b6f-d1da-40dd-9bc2-561f26a8a5d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'name' and @type = 'text']</value>
      <webElementGuid>457ed1d5-4d40-41f6-a4f4-6c446ddffac7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
