<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_search_menuQuickSearchmenuQuickSearch</name>
   <tag></tag>
   <elementGuidId>317e8db9-02f0-4735-b547-b786bc470afc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menuQuickSearch_menuQuickSearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='menuQuickSearch_menuQuickSearch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b6eb793f-2e9b-4ff3-842a-3851bc07ea08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>cbb71496-e097-40be-9088-b74c615a12dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8ff4b572-0a43-443c-877f-6bb2a407bca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>menuQuickSearch[menuQuickSearch]</value>
      <webElementGuid>0caabcbd-08d1-4292-856e-59bf4fa5ee1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menuQuickSearch_menuQuickSearch</value>
      <webElementGuid>7aab16b6-62a4-4167-9f62-07e7224705e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>menuQuickSearchResultList</value>
      <webElementGuid>a8e8fec1-1e67-40d8-86b6-41be5b9b596b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>both</value>
      <webElementGuid>fd3e4767-bc2f-4427-a629-a307a859b1b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menuQuickSearch_menuQuickSearch&quot;)</value>
      <webElementGuid>bceb34a7-8848-4ba6-8642-03f6d084830f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='menuQuickSearch_menuQuickSearch']</value>
      <webElementGuid>ea2af81a-0326-43ac-b99b-59d3b9326152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='left-menu']/div[3]/div[2]/input</value>
      <webElementGuid>841c7b81-7492-4d89-911c-abb2d58c7b97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8d6fde45-643c-4ae6-ab45-b3d84b23a6f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Search' and @type = 'text' and @name = 'menuQuickSearch[menuQuickSearch]' and @id = 'menuQuickSearch_menuQuickSearch']</value>
      <webElementGuid>f2a31654-fe2f-4321-823d-b6cecb027220</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
