<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_dad</name>
   <tag></tag>
   <elementGuidId>acc2f3bc-e77f-462a-b42e-a56cde7fa0a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td[name=&quot;listField.name&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@name='listField.name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;dad&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>7c3e7f6d-6f94-4dcb-9c05-3b07b2bfb9f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>((obj[list.clickableCondition] &amp;&amp; list.clickableCondition)||!list.clickableCondition) &amp;&amp; (listField.hideField==true?false:true)</value>
      <webElementGuid>9e9baf81-e405-4ae3-a9dd-f11dadbf7837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-repeat</name>
      <type>Main</type>
      <value>listField in listData.listFields</value>
      <webElementGuid>b5148a21-476b-4f7f-882b-49e096fa7d7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-style</name>
      <type>Main</type>
      <value>getStyle(obj, listField.style)</value>
      <webElementGuid>744c410d-c800-44ba-b79d-0d0f26e87d60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{truncate: listField.truncate, tooltipped: listField.truncate, 'cursor-pointer': listField.clickAction}</value>
      <webElementGuid>6a3c40a5-3192-4d74-b9a7-4199f417c8a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-data-tooltip</name>
      <type>Main</type>
      <value>{{listField.truncate ? getFieldValue(obj, listField.getter, listField.formatter, listField.filters) : undefined}}</value>
      <webElementGuid>adb3c703-3e29-4fe6-8ad8-8567a8f1e6af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-data-position</name>
      <type>Main</type>
      <value>{{listField.truncate ? 'bottom' : undefined}}</value>
      <webElementGuid>f21c7be3-f9e3-4d75-b17a-4cfd68a47b75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>list.runAction(listField.clickAction, obj, listField)</value>
      <webElementGuid>00e3a4de-89db-480c-8782-c04c01c8c8c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data</name>
      <type>Main</type>
      <value>getFieldValue(obj, listField.getter, listField.formatter, listField.filters)</value>
      <webElementGuid>234bf57c-f8e7-4935-9c50-d872ca1159b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rowid</name>
      <type>Main</type>
      <value>obj.id</value>
      <webElementGuid>30d549ca-41f7-4c21-8457-d5e121af7226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>listField.name</value>
      <webElementGuid>7cf1fa6a-7af9-477b-aa65-acc38a748d0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>listField.type</value>
      <webElementGuid>cabe5f57-689a-4ab0-aadb-01e0c664dcee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>extracontroller</name>
      <type>Main</type>
      <value>extracontroller</value>
      <webElementGuid>f1db63f5-8ee4-465a-bbdc-cd9926ab2739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>url</name>
      <type>Main</type>
      <value>getFieldValue(obj, listField.getter, listField.formatter, listField.filters, listField.link)</value>
      <webElementGuid>c012d870-e2dc-4592-9ea7-7f45ed14f5cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>dad</value>
      <webElementGuid>722cf080-4e80-40b2-beb4-6d89fc14b580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;educationsDiv&quot;)/crud-panel[1]/div[@class=&quot;form-div&quot;]/div[@class=&quot;list-container&quot;]/list[1]/table[@class=&quot;highlight bordered&quot;]/tbody[1]/tr[1]/td[2]</value>
      <webElementGuid>d9d6d331-234c-4e51-8b92-add0271a0ec1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@name='listField.name']</value>
      <webElementGuid>773240be-5559-42db-9732-8fe55a936ee6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='educationsDiv']/crud-panel/div/div/list/table/tbody/tr/td[2]</value>
      <webElementGuid>304bc9ec-caff-48e4-b65e-f8e4afc275db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='arrow_upward'])[1]/following::td[2]</value>
      <webElementGuid>c913737b-4096-4518-9cb0-fcd2cb5e5ade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ohrm_edit'])[1]/preceding::td[1]</value>
      <webElementGuid>7b21b03e-5427-476e-87d7-4c2e71eb0ecf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]</value>
      <webElementGuid>64723ec5-eac1-40aa-9f34-1b26b371189f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@name = 'listField.name' and @type = 'listField.type' and (text() = 'dad' or . = 'dad')]</value>
      <webElementGuid>0b54103d-5566-4537-b3a9-9ea1bdea6956</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
